### ISSUE TITLE
Organización del repositorio

### ISSUE THREAD

**Issue by bustamante-jt** [JulietaCaceres/TPDragonBall#2]
- La estructura de los subdirectorios y paquetes debe ser acorde al [proyecto base](https://github.com/fiuba/ProyectoBaseAlgo3).
- Faltan los archivos `ivy.xml` y `build.xml` necesarios para la compilación y ejecución con Ant.
- No debe haber archivos `.class` en el repositorio, solo `.java`.

**Comment by JulietaCaceres** [comment]
Hola Tomas! 
Estuvimos pensando acerca de las evoluciones de los personajes. Inicialmente lo hicimos usando el patron de diseño State que vimos en clases. Con lo cual terminamos creando 16 clases EstadoGoku, EstadoKaioKen,etc, para cada personaje, luego vimos que eran demasiadas y pensamos en hacer 3 (que heredan de Estado) : EstadoNormal, EstadoPrimeraTransformacion, EstadoTerceraTransformacion, que reciben en su constructor los valores de poder, distancia y velocidad, al momento de ser creados de acuerdo a cada personaje  . Pero vimos que de una u otra forma, todos los estados hacian lo mismo, con la diferencia de que cada uno tenia una magnitud diferente en sus atributos de poder o velocidad. Lo cual nos derivo a la siguiente pregunta, ¿se podria crear una unica clase Estado que en el constructor reciba como parametro los valores de estos atributos y cada vez que un personaje quiera transformarse utilice el constructor con sus respectivos valores?¿esta bueno que personaje   dé los valores de su estado futuro?¿si bien esto funcionaria, estariamos usando un modelo acorde al objetivo del trabajo practico?

**Comment by bustamante-jt** [comment]
- Los archivos `.classpath` y `.project` no deben estar en el repositorio.
- Los subdirectorios `.metadata`, `.recommenders` y bin tampoco.
